'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace wsCondiciones
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Registro", [Namespace]:="http://schemas.datacontract.org/2004/07/wsCondiciones"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Registro
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AzulField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContactoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmpleadoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdentificacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PruebaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SintomasField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoIdeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Azul() As Boolean
            Get
                Return Me.AzulField
            End Get
            Set
                If (Me.AzulField.Equals(value) <> true) Then
                    Me.AzulField = value
                    Me.RaisePropertyChanged("Azul")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Contacto() As Boolean
            Get
                Return Me.ContactoField
            End Get
            Set
                If (Me.ContactoField.Equals(value) <> true) Then
                    Me.ContactoField = value
                    Me.RaisePropertyChanged("Contacto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Empleado() As Boolean
            Get
                Return Me.EmpleadoField
            End Get
            Set
                If (Me.EmpleadoField.Equals(value) <> true) Then
                    Me.EmpleadoField = value
                    Me.RaisePropertyChanged("Empleado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Identificacion() As String
            Get
                Return Me.IdentificacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdentificacionField, value) <> true) Then
                    Me.IdentificacionField = value
                    Me.RaisePropertyChanged("Identificacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Prueba() As Boolean
            Get
                Return Me.PruebaField
            End Get
            Set
                If (Me.PruebaField.Equals(value) <> true) Then
                    Me.PruebaField = value
                    Me.RaisePropertyChanged("Prueba")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Sintomas() As Boolean
            Get
                Return Me.SintomasField
            End Get
            Set
                If (Me.SintomasField.Equals(value) <> true) Then
                    Me.SintomasField = value
                    Me.RaisePropertyChanged("Sintomas")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoIde() As String
            Get
                Return Me.TipoIdeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoIdeField, value) <> true) Then
                    Me.TipoIdeField = value
                    Me.RaisePropertyChanged("TipoIde")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="wsCondiciones.IwsCondiciones")>  _
    Public Interface IwsCondiciones
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsCondiciones/Set_Ingreso", ReplyAction:="http://tempuri.org/IwsCondiciones/Set_IngresoResponse")>  _
        Function Set_Ingreso(ByVal regCondicion As wsCondiciones.Registro) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsCondiciones/Set_Ingreso", ReplyAction:="http://tempuri.org/IwsCondiciones/Set_IngresoResponse")>  _
        Function Set_IngresoAsync(ByVal regCondicion As wsCondiciones.Registro) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsCondiciones/Inicializar", ReplyAction:="http://tempuri.org/IwsCondiciones/InicializarResponse")>  _
        Function Inicializar() As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsCondiciones/Inicializar", ReplyAction:="http://tempuri.org/IwsCondiciones/InicializarResponse")>  _
        Function InicializarAsync() As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IwsCondicionesChannel
        Inherits wsCondiciones.IwsCondiciones, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class IwsCondicionesClient
        Inherits System.ServiceModel.ClientBase(Of wsCondiciones.IwsCondiciones)
        Implements wsCondiciones.IwsCondiciones
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Set_Ingreso(ByVal regCondicion As wsCondiciones.Registro) As Boolean Implements wsCondiciones.IwsCondiciones.Set_Ingreso
            Return MyBase.Channel.Set_Ingreso(regCondicion)
        End Function
        
        Public Function Set_IngresoAsync(ByVal regCondicion As wsCondiciones.Registro) As System.Threading.Tasks.Task(Of Boolean) Implements wsCondiciones.IwsCondiciones.Set_IngresoAsync
            Return MyBase.Channel.Set_IngresoAsync(regCondicion)
        End Function
        
        Public Function Inicializar() As Boolean Implements wsCondiciones.IwsCondiciones.Inicializar
            Return MyBase.Channel.Inicializar
        End Function
        
        Public Function InicializarAsync() As System.Threading.Tasks.Task(Of Boolean) Implements wsCondiciones.IwsCondiciones.InicializarAsync
            Return MyBase.Channel.InicializarAsync
        End Function
    End Class
End Namespace
